import { useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, Briefcase, CalendarDays, CheckCircle2, CircleHelp, Download, ExternalLink, IndianRupee, MapPin, Star, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { companies } from "@/data/companies";
import { applicationKey, usePortalStore } from "@/store/portalStore";

export default function CompanyDetailsPage() {
  const [params] = useSearchParams();
  const companyId = params.get("companyid");
  const company = companies[companyId];
  const [question, setQuestion] = useState("");
  const savedThreads = usePortalStore((state) => state.companyThreads[companyId]);
  const addQuestion = usePortalStore((state) => state.addCompanyQuestion);
  const applications = usePortalStore((state) => state.applications);
  const applyToRole = usePortalStore((state) => state.applyToRole);
  if (!company) return <Card className="mx-auto max-w-lg text-center"><CardContent className="pt-8"><h1 className="text-xl font-bold">Company not found</h1><Button asChild className="mt-5"><Link to="/student/companies">Browse companies</Link></Button></CardContent></Card>;
  const threads = savedThreads || company.questions || [];
  const faqs = company.faqs || [{ question: "Where can I find the official drive details?", answer: "The placement cell will share the official drive brief with eligible students." }];
  const submitQuestion = (event) => { event.preventDefault(); if (!question.trim()) return; addQuestion(companyId, question.trim(), company.questions || []); setQuestion(""); };
  return <div className="mx-auto max-w-5xl space-y-6"><Link to="/student/companies" className="inline-flex items-center gap-2 text-sm font-semibold text-indigo-600"><ArrowLeft className="h-4 w-4" />All companies</Link>
    <section className="rounded-3xl bg-gradient-to-br from-indigo-700 to-violet-700 p-7 text-white sm:p-9"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-indigo-200">Company profile</p><h1 className="mt-2 text-4xl font-bold">{company.name}</h1><p className="mt-3 flex items-center gap-2 text-indigo-100"><MapPin className="h-4 w-4" />{company.location}</p></div><a href={company.glassdoor} target="_blank" rel="noreferrer" className="flex h-fit w-fit items-center gap-2 rounded-xl bg-white/15 px-3 py-2 text-sm font-semibold"><Star className="h-4 w-4 fill-amber-300 text-amber-300" />Glassdoor {company.rating}<ExternalLink className="h-3.5 w-3.5" /></a></div></section>
    <Card><CardHeader><CardTitle>About {company.name}</CardTitle></CardHeader><CardContent><p className="leading-7 text-muted-foreground">{company.overview}</p><h3 className="mt-6 font-semibold">Work culture</h3><p className="mt-2 leading-7 text-muted-foreground">{company.workCulture}</p><div className="mt-5 flex flex-wrap gap-2">{company.skills.map((skill) => <span key={skill} className="rounded-full bg-indigo-50 px-3 py-1 text-sm font-medium text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">{skill}</span>)}</div></CardContent></Card>
    <Card><CardHeader className="flex-row items-center justify-between gap-4"><div><CardTitle>Open roles</CardTitle><p className="mt-1 text-sm text-muted-foreground">Review the requirements before submitting. Applications are tracked in your workspace.</p></div>{companyId === "google" && <Button asChild variant="outline"><a href="/drive-briefs/google-campus-drive-brief.pdf" target="_blank" rel="noreferrer"><Download className="mr-2 h-4 w-4" />Drive PDF</a></Button>}</CardHeader><CardContent className="space-y-4">{company.roles.map((role) => { const applied = applications.some((item) => item.id === applicationKey(companyId, role.title)); return <article key={role.title} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><h3 className="text-lg font-semibold">{role.title}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{role.description}</p></div><div className="flex h-fit flex-wrap gap-2"><Button asChild variant="outline"><a href={companyId === "google" ? "/drive-briefs/google-campus-drive-brief.pdf" : company.website} target="_blank" rel="noreferrer">Open JD</a></Button><Button disabled={applied} onClick={() => applyToRole({ companySlug: companyId, company: company.name, role: role.title })} className="bg-indigo-600 text-white hover:bg-indigo-700">{applied ? <><CheckCircle2 className="mr-2 h-4 w-4" />Applied</> : "Apply now"}</Button></div></div><div className="mt-5 grid gap-3 border-t border-slate-200 pt-4 text-sm dark:border-slate-800 sm:grid-cols-3"><span className="flex items-center gap-2"><IndianRupee className="h-4 w-4 text-indigo-600" />{role.package}</span><span className="flex items-center gap-2"><Briefcase className="h-4 w-4 text-indigo-600" />{role.eligibility}</span><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-indigo-600" />{role.date}</span></div></article>; })}</CardContent></Card>
    <Card className="border-indigo-100 bg-indigo-50/40 dark:border-indigo-950 dark:bg-indigo-950/20"><CardHeader><CardTitle>Placement cell insight</CardTitle></CardHeader><CardContent className="grid gap-6 sm:grid-cols-3"><div><p className="flex items-center gap-2 font-semibold"><Users className="h-4 w-4 text-indigo-600" />Student volunteer POC</p><p className="mt-2 font-medium">{company.poc.name}</p><a href={`mailto:${company.poc.email}`} className="text-sm text-indigo-600 hover:underline">{company.poc.email}</a></div><div><p className="font-semibold">Previous campus results</p><p className="mt-2 text-2xl font-bold">{company.outcomes.selected}</p><p className="text-sm text-muted-foreground">selected in {company.outcomes.year}</p></div><div><p className="font-semibold">Expected package range</p><p className="mt-2 text-2xl font-bold">{company.outcomes.package}</p><p className="text-sm text-muted-foreground">Varies by role and evaluation</p></div></CardContent></Card>
    {company.alumni?.length > 0 && <Card><CardHeader><CardTitle>Alumni outcomes</CardTitle><p className="text-sm text-muted-foreground">Placement-cell supplied records</p></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3">{company.alumni.map((student) => <div className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-800" key={student.name}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-indigo-100 text-sm font-bold text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300" aria-hidden="true">{student.initials}</span><div><p className="text-sm font-semibold">{student.name}</p><p className="text-xs text-muted-foreground">{student.role} · {student.year}</p><p className="text-xs font-semibold text-emerald-600">{student.package}</p></div></div>)}</CardContent></Card>}
    <Card><CardHeader><CardTitle>Company FAQs</CardTitle></CardHeader><CardContent className="space-y-3">{faqs.map((faq) => <details className="rounded-xl border border-slate-200 p-4 dark:border-slate-800" key={faq.question}><summary className="font-semibold">{faq.question}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{faq.answer}</p></details>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CircleHelp className="h-5 w-5 text-indigo-600" />Drive Q&A</CardTitle><p className="text-sm text-muted-foreground">Questions and reply threads from students, alumni and the placement cell.</p></CardHeader><CardContent><div className="space-y-4">{threads.map((thread, index) => <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-800" key={`${thread.author}-${index}`}><p className="text-xs font-bold text-indigo-600">{thread.author} asked</p><p className="mt-1 text-sm font-medium">{thread.text}</p>{thread.replies?.map((reply, replyIndex) => <div className="mt-3 border-l-2 border-indigo-200 pl-3" key={`${reply.author}-${replyIndex}`}><p className="text-xs font-bold text-emerald-600">{reply.author} replied</p><p className="mt-1 text-sm text-muted-foreground">{reply.text}</p></div>)}</div>)}</div><form className="mt-5 flex gap-2" onSubmit={submitQuestion}><Input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask a question about this company" /><Button type="submit" className="bg-indigo-600 text-white hover:bg-indigo-700">Post question</Button></form></CardContent></Card>
  </div>;
}
