import { ArrowRight, Award, BriefcaseBusiness, CalendarDays, CheckCircle2, FileCheck2, Search, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

const features = [
  { icon: Search, title: "Discover the right roles", text: "Explore verified campus opportunities that suit your skills and goals." },
  { icon: FileCheck2, title: "Apply with confidence", text: "Keep your profile, resume and applications organised in one place." },
  { icon: CalendarDays, title: "Never miss a drive", text: "Stay ahead with timely updates about interviews, tests and deadlines." },
];

export default function LandingPage() {
  return (
    <main className="overflow-hidden bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-50">
      <section className="relative isolate border-b border-indigo-100 bg-gradient-to-br from-indigo-50 via-white to-violet-100 px-5 py-16 dark:border-indigo-950 dark:from-slate-950 dark:via-slate-950 dark:to-indigo-950 sm:px-6 lg:py-24">
        <div className="absolute inset-0 -z-10 opacity-40 [background-image:radial-gradient(#818cf8_1px,transparent_1px)] [background-size:24px_24px]" />
        <div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
          <div className="max-w-2xl">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-white/80 px-3.5 py-1.5 text-sm font-medium text-indigo-700 shadow-sm dark:border-indigo-800 dark:bg-slate-900/80 dark:text-indigo-300"><Sparkles className="h-4 w-4" /> Your career journey starts here</div>
            <h1 className="text-4xl font-bold leading-[1.08] tracking-tight sm:text-5xl lg:text-6xl">Where ambition meets <span className="bg-gradient-to-r from-indigo-600 to-violet-600 bg-clip-text text-transparent">opportunity.</span></h1>
            <p className="mt-6 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">Build a profile that stands out, find campus opportunities that matter, and take the next confident step toward your career.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 bg-indigo-600 px-6 text-white shadow-lg shadow-indigo-500/25 hover:bg-indigo-700"><Link to="/signup">Create your profile <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild size="lg" variant="outline" className="h-12 border-slate-300 bg-white/70 px-6 dark:bg-slate-900"><Link to="/login">Sign in to portal</Link></Button></div>
            <div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm font-medium text-slate-600 dark:text-slate-300">{["Verified opportunities", "One streamlined profile", "Timely drive alerts"].map((item) => <span className="flex items-center gap-2" key={item}><CheckCircle2 className="h-4 w-4 text-emerald-500" />{item}</span>)}</div>
          </div>
          <div className="relative mx-auto min-w-0 w-full max-w-lg"><div className="absolute -inset-6 -z-10 rounded-full bg-indigo-400/25 blur-3xl" /><div className="overflow-hidden rounded-3xl border border-white/80 bg-white/85 p-4 shadow-2xl shadow-indigo-950/15 backdrop-blur dark:border-slate-700 dark:bg-slate-900/90 sm:p-5"><div className="flex items-center justify-between border-b border-slate-100 pb-4 dark:border-slate-800"><div><p className="text-xs font-semibold uppercase tracking-widest text-indigo-600">Career dashboard</p><p className="mt-1 font-semibold">Good morning, Alex</p></div><div className="rounded-xl bg-indigo-50 p-2.5 text-indigo-600 dark:bg-indigo-950"><BriefcaseBusiness className="h-5 w-5" /></div></div><div className="mt-5 grid grid-cols-3 gap-2 sm:gap-3">{[["08", "Open roles"], ["03", "Applications"], ["91%", "Profile"]].map(([value, label]) => <div className="min-w-0 rounded-2xl bg-slate-50 p-2.5 sm:p-3 dark:bg-slate-800" key={label}><p className="text-xl font-bold">{value}</p><p className="mt-1 truncate text-[11px] text-slate-500 sm:text-xs">{label}</p></div>)}</div><div className="mt-5 rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50 to-violet-50 p-4 dark:border-indigo-900 dark:from-indigo-950/60 dark:to-violet-950/40"><div className="flex items-start justify-between"><div className="min-w-0"><p className="text-sm font-semibold">Product Intern</p><p className="mt-1 truncate text-xs text-slate-500">Northstar Technologies · Pune</p></div><span className="ml-2 rounded-full bg-white px-2 py-1 text-[10px] font-bold text-indigo-600 dark:bg-slate-800">NEW</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-indigo-100 dark:bg-indigo-900"><div className="h-full w-[78%] rounded-full bg-indigo-500" /></div><p className="mt-2 text-xs text-slate-500">Application closes in 4 days</p></div><div className="mt-4 flex items-center gap-3 rounded-2xl border border-slate-100 p-3 dark:border-slate-800"><div className="rounded-lg bg-emerald-100 p-2 text-emerald-600 dark:bg-emerald-950"><Award className="h-4 w-4" /></div><div className="min-w-0"><p className="truncate text-sm font-medium">Profile strength is excellent</p><p className="text-xs text-slate-500">You&apos;re ready to apply.</p></div></div></div></div>
        </div>
      </section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-6"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[.18em] text-indigo-600">Designed for your next step</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Everything you need to move forward.</h2><p className="mt-4 text-slate-600 dark:text-slate-300">A simple, focused space to manage every part of your campus placement journey.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article className="group rounded-2xl border border-slate-200 bg-white p-7 transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-xl hover:shadow-indigo-950/5 dark:border-slate-800 dark:bg-slate-900 dark:hover:border-indigo-800" key={title}><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-100 text-indigo-600 transition group-hover:bg-indigo-600 group-hover:text-white dark:bg-indigo-950"><Icon className="h-5 w-5" /></div><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-600 dark:text-slate-300">{text}</p></article>)}</div></section>
      <section className="border-y border-slate-200 bg-white px-5 py-16 dark:border-slate-800 dark:bg-slate-900 sm:px-6"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-2"><div className="rounded-3xl bg-slate-950 p-7 text-white sm:p-9"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-500/20 text-indigo-300"><UsersRound className="h-5 w-5" /></span><p className="mt-6 text-sm font-bold uppercase tracking-[.18em] text-indigo-300">For students</p><h2 className="mt-2 text-2xl font-bold">Know what&apos;s next, not just what&apos;s open.</h2><p className="mt-3 leading-7 text-slate-300">See eligibility, deadlines, application stages and upcoming selection rounds in one clear journey.</p></div><div className="rounded-3xl border border-indigo-100 bg-indigo-50 p-7 dark:border-indigo-900 dark:bg-indigo-950/30 sm:p-9"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white text-indigo-600 shadow-sm dark:bg-slate-900"><ShieldCheck className="h-5 w-5" /></span><p className="mt-6 text-sm font-bold uppercase tracking-[.18em] text-indigo-600">For placement teams</p><h2 className="mt-2 text-2xl font-bold">Run every drive from a trusted workspace.</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">Manage applicants, verify eligibility, assign owners and report outcomes without scattered spreadsheets.</p></div></div></section>
      <section className="px-5 py-20 sm:px-6"><div className="mx-auto max-w-5xl overflow-hidden rounded-3xl bg-gradient-to-r from-indigo-700 to-violet-700 px-7 py-12 text-center text-white shadow-xl shadow-indigo-950/20 sm:px-12"><p className="text-sm font-semibold uppercase tracking-[.18em] text-indigo-200">Your future, in motion</p><h2 className="mx-auto mt-3 max-w-2xl text-3xl font-bold tracking-tight sm:text-4xl">Take the first step toward the role you&apos;ve been working for.</h2><p className="mx-auto mt-4 max-w-xl text-indigo-100">Set up your profile today and keep every opportunity within reach.</p><Button asChild size="lg" className="mt-8 h-12 bg-white px-6 text-indigo-700 hover:bg-indigo-50"><Link to="/signup">Get started now <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
    </main>
  );
}
